# Generated by Django 2.2.2 on 2019-06-06 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Restaurante')),
                ('descr', models.TextField(max_length=240, verbose_name='Descripción del restaurante')),
                ('logo', models.ImageField(upload_to='uploaded_img/logos/', verbose_name='Logotipo')),
                ('banner', models.ImageField(upload_to='uploaded_img/restaurants/', verbose_name='Foto de cabecera')),
                ('telefono', models.IntegerField(blank=True, default=None, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, default='', max_length=15, verbose_name='Teléfono de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('lat', models.DecimalField(decimal_places=7, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Latitud')),
                ('long', models.DecimalField(decimal_places=7, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='restaurantes.Restaurante')),
            ],
        ),
    ]
