# Generated by Django 2.2 on 2019-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Restaurante')),
                ('descr', models.TextField(max_length=240, verbose_name='Nombre del plan')),
                ('logo', models.ImageField(upload_to='uploaded_img/logos/')),
                ('banner', models.ImageField(upload_to='uploaded_img/restaurants/')),
            ],
        ),
    ]
