# Generated by Django 2.2 on 2019-06-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='telefono',
        ),
    ]
