# Generated by Django 2.2 on 2019-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20190606_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=15, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='telefono',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
