# Generated by Django 2.2 on 2019-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20190606_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=15, verbose_name='Email de contacto'),
        ),
    ]
