# Generated by Django 2.2 on 2019-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagtext', models.CharField(default='', max_length=30, verbose_name='Tag')),
                ('restaurante', models.ManyToManyField(related_name='tags', to='cartas.Plato')),
            ],
        ),
    ]
