# Generated by Django 2.2 on 2019-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0002_plato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='lista_ingredientes',
            field=models.TextField(blank=True, max_length=240, verbose_name='Lista de ingredientes'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del plato'),
        ),
    ]
