# Generated by Django 2.2 on 2019-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0003_auto_20190603_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(max_length=240, verbose_name='Descripción'),
        ),
    ]
