# Generated by Django 2.2 on 2019-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('max_empresas', models.IntegerField(default=0)),
                ('max_categorias', models.IntegerField(default=1)),
                ('max_productos_x_cat', models.IntegerField(default=5)),
                ('max_tags_x_prod', models.IntegerField(default=3)),
                ('permite_anuncios', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
