# Generated by Django 2.2 on 2019-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del plan')),
                ('max_empresas', models.IntegerField(default=0, verbose_name='Max de empresas (0 = infinito)')),
                ('max_categorias', models.IntegerField(default=1, verbose_name='Max categorías por empresa (0 = infinito)')),
                ('max_productos_x_cat', models.IntegerField(default=5, verbose_name='Max productos por categoría (0 = infinito)')),
                ('max_tags_x_prod', models.IntegerField(default=3, verbose_name='Max tag x producto (0= infinito)')),
                ('permite_anuncios', models.BooleanField(default=False, verbose_name='Permitir crear anuncios')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('class_descr', models.CharField(choices=[('free', 'Blanco'), ('standard', 'Naranja'), ('blue', 'Azul')], default='free', max_length=10, verbose_name='Clase CSS Descriptiva')),
                ('recomendado', models.BooleanField(default='False', verbose_name='Mostrar como recomendado')),
                ('recomendado_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto de recomendación')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
    ]
