# Generated by Django 2.2 on 2019-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='class_descr',
            field=models.CharField(default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='recomendado',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='plan',
            name='recomendado_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
