# Generated by Django 2.2 on 2019-04-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190420_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plan',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
