# Generated by Django 2.2 on 2019-04-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190420_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
