# Generated by Django 2.2 on 2019-05-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
        ('accounts', '0004_auto_20190420_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurante',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante'),
        ),
    ]
